[project]
name = "laundry-monitor"
version = "0.1.0"
description = "Laundry Monitor backend and Streamlit frontend"
readme = "README.md"
requires-python = ">=3.11,<4.0"
authors = [
  { name = "Ilia Kliantsevich" },
  { name = "Amirkhan Kurbanov" },
  { name = "Rashid Badamshin" },
  { name = "Aidar Sarvartdinov" },
  { name = "Damir Sadykov" },
]
dependencies = [
    "fastapi>=0.116.0,<0.117.0",
    "pydantic>=2.0.0,<3.0.0",
    "sqlalchemy>=2.0.36,<3.0.0",
    "uvicorn>=0.35.0,<0.36.0",
    "httpx>=0.28.1,<0.29.0",
    "streamlit>=1.44.1,<2.0.0",
]

[tool.poetry]
packages = [
    { include = "backend", from = "src" },
    { include = "frontend", from = "src" },
]

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.4"
pytest-cov = "^5.0.0"
ruff = "^0.11.0"
flake8 = "^7.1.1"
bandit = "^1.7.9"
radon = "^6.0.1"
locust = "^2.31.8"
pre-commit = "^4.0.1"

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]

[tool.ruff]
line-length = 100
target-version = "py311"

[build-system]
requires = ["poetry-core>=1.9.0"]
build-backend = "poetry.core.masonry.api"
